#!/bin/bash

CDIR="$(pwd)"
export PATH="${CDIR}/gcc-arm/bin:$PATH"
export ARCH="arm"
COMPILER_PREFIX="arm-linux-gnueabihf"
export CROSS_COMPILE="${COMPILER_PREFIX}-"
export CC="${CROSS_COMPILE}gcc"
export CXX="${CROSS_COMPILE}g++"
export CPP="${CROSS_COMPILE}g++"
export AR="${CROSS_COMPILE}ar"
export AS="${CROSS_COMPILE}as"
export RANLIB="${CROSS_COMPILE}ranlib"
export LD="${CROSS_COMPILE}ld"
export STRIP="${CROSS_COMPILE}strip"
